### PR TITLE
Add parallel computation option for `parboot` function

### PR DESCRIPTION
**Pull request by adamdsmith**
I've added the capability to generate bootstrapped test statistics on multiple cores using package `parallel`.  Parallel computation is the default option so long as more than two cores are present on the machine (`parboot` uses nCores - 1) and the requested number of simulations is >= 100 (the approximate point at which parallel computation is advantageous).

I've tested it successfully on the following `unmarkedFit`s: MPois and GMM (with and without a custom `piFun`), DS and GDS, PCount, GPC, and PCO, and Occu.

It does not work for `unmarkedFit`s  without a `simulate` method (e.g., OccuPEN) or with `fitted` or `residuals` methods (e.g., OccuFP).

I've changed the DESCRIPTION and NAMESPACE files to reflect the `parallel` package dependency.  

I also updated parboot.Rd file to reflect the new arguments related to parallel computation.

### CODE REVIEW

**Comment by rbchan** [comment]
This is great. Can you also add some tests to inst/unitTests/?

**Comment by adamdsmith** [comment]
Sure.  I've not done them before, so your patience is appreciated.  Do you want one for each class of unmarkedFit?

**Comment by rbchan** [comment]
Just one test would be fine. Ideally, the test should only take a few seconds to run, so consider doing it on an occu fit. The entire suite of tests can be run using: `source("runTests.R")`. Thanks again.

**Comment by adamdsmith** [comment]
Hope this test is sufficient.  I have not tested the parallel application on Mac/Linux, but it should work.

**Comment by jaroyle** [comment]
hi Adam,
 Thanks for this!
 I'll try to do the merge this week and then test it out myself (in
meetings all day between now and Thursday morning, so probably end of the
week)
regards
andy

**Comment by rbchan** [comment]
Thanks Adam. Merged now.

**Pull request merged**
